---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figure/",
  fig.height = 1
)
```

# Wes Anderson Palettes (modified)




## Installation

```r
devtools::install_github("devanmcg/wesanderson")
```

## Usage

```{r, palettes_dummy, eval = FALSE}
library("wesanderson")
```

```{r echo=FALSE}
pacman::p_load_gh("devanmcg/wesanderson")
```

```{r}
# See all palettes
names(wes_palettes)
```

## Palettes

### Bottle Rocket (1996)

```{r, bottlerocket1}
wes_palette("BottleRocket1")
wes_palette("BottleRocket2")
```

### Rushmore (1998)

```{r, rushmore}
wes_palette("Rushmore1")
```

### The Royal Tenenbaums (2001)

```{r, royal}
wes_palette("Royal1")
wes_palette("Royal2")
```

```{r, ggplot1, fig.height = 3}
library("ggplot2")
ggplot(mtcars, aes(factor(cyl), fill=factor(vs))) +  geom_bar() +
  scale_fill_manual(values = wes_palette("Royal1"))
```

### The Life Aquatic with Steve Zissou (2004)

```{r, lifeaquatic}
wes_palette("Zissou1")
```


```{r, volcano, fig.height = 3}
pal <- wes_palette("Zissou1", 21, type = "continuous")
image(volcano, col = pal)
```

```{r, zissou_heatmap, fig.height = 3}
pal <- wes_palette("Zissou1", 100, type = "continuous")
# heatmap is a local dataset
ggplot(heatmap, aes(x = X2, y = X1, fill = value)) +
  geom_tile() + 
  scale_fill_gradientn(colours = pal) + 
  scale_x_discrete(expand = c(0, 0)) +
  scale_y_discrete(expand = c(0, 0)) + 
  coord_equal() 
```

### The Darjeeling Limited (2007)

```{r, darjeeling}
wes_palette("Darjeeling1")
wes_palette("Darjeeling2")
```

### Hotel Chevalier (2007)

```{r, chevalier}
wes_palette("Chevalier1")
```

### Fantastic Mr. Fox (2009)

```{r, fantasticfox}
wes_palette("FantasticFox1")
```

### Moonrise Kingdom (2012)

```{r, moonrise}
wes_palette("Moonrise1")
wes_palette("Moonrise2")
wes_palette("Moonrise3")
```

### Castello Cavalcanti (2013)

```{r, castello}
wes_palette("Cavalcanti1")
```

### The Grand Budapest Hotel (2014)

```{r, grandbudapest}
wes_palette("GrandBudapest1")
wes_palette("GrandBudapest2")
```


### The Isle of Dogs (2018)

```{r, isleofdogs}
wes_palette("IsleofDogs1")
wes_palette("IsleofDogs2")
```

